spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"  # Frontend URL
            allowedMethods: 
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: User_Input
          uri: http://localhost:8080
          predicates:
            - Path=/api/inputs/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: user

        - id: CostEstimator
          uri: http://localhost:8081
          predicates:
            - Path=/api/cost-estimates/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: user

        - id: Materials
          uri: http://localhost:8083
          predicates:
            - Path=/api/materials/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: user

        - id: ConstructionService
          uri: http://localhost:9093
          predicates:
            - Path=/api/constructors/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: user

        - id: reportsService
          uri: http://localhost:8084
          predicates:
            - Path=/api/reports/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: user

        - id: User-service
          uri: http://localhost:9091
          predicates:
            - Path=/users/**
